// src/app/shared/general-components/page-wrapper/page-wrapper.component.ts
import { Component } from '@angular/core';
import { languages } from '../../constants';

@Component({
  selector: 'tx-page-wrapper',
  templateUrl: './page-wrapper.component.html',
  styleUrls: ['./page-wrapper.component.scss'],
})
export class PageWrapperComponent {
  public isLoggedIn: boolean = false;
  public languageList = languages;
}

<div class="page-wrapper">
  <header class="page-wrapper__header">
    <div class="page-wrapper__functionality-block" [ngClass]="{ 'functionality-block_logged-out': !(isUserSignedUp$|async) && !(accessToken$|async) }">
      <tx-dropdown-menu [items]="languageList"></tx-dropdown-menu>
      <a *ngIf="(isUserSignedUp$|async) || (accessToken$|async)" class="page-wrapper__sign-in-link" href="#">Log Out</a>
    </div>
    <h1 *ngIf="(isUserSignedUp$|async) || (accessToken$|async)" class="page-wrapper__title">GeneralSoft Taxi</h1>
  </header>
  <section class="page-wrapper__content">
    <ng-content></ng-content>
  </section>
</div>

// components/generalComponents/PageWrapper/PageWrapper.tsx
import { FC, ReactNode } from "react";

import styles from "../PageWrapper.module.scss";

type pageWrapperProps = {
    children: ReactNode;
};

const PageWrapper: FC<pageWrapperProps> = ({ children }) => {
    let isLoggedIn: boolean = true;

    return (
        <div className={styles["page-wrapper"]}>
            <header className={styles["page-wrapper__header"]}>
                <div
                    className={`${
                        styles["page-wrapper__functionality-block"]
                    } ${
                        !isLoggedIn
                            ? styles["functionality-block_logged-out"]
                            : null
                    }`}
                >
                    {/* TODO: temporary until we do not have dropdown menu component */}
                    <div className="page-wrapper__languages-list languages-list">
                        <span>English ↓</span>
                    </div>
                    {isLoggedIn ? (
                        <a
                            className={styles["page-wrapper__sign-in-link"]}
                            href="#"
                        >
                            Log Out
                        </a>
                    ) : (
                        <></>
                    )}
                </div>
                {isLoggedIn ? (
                    <h1 className={styles["page-wrapper__title"]}>
                        GeneralSoft Taxi
                    </h1>
                ) : (
                    <></>
                )}
            </header>
            <section className={styles["page-wrapper__content"]}>
                {children}
            </section>
        </div>
    );
};

export default PageWrapper;
